Fix workflow

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -21,19 +21,19 @@ jobs:
 
       - name: Run coding style checker
         run: |
-          check.sh $(pwd) $(pwd)
-          grep --invert-match "./libs/myteams" coding-style-reports.log | while IFS= read -r line; do
-            file=$(echo "$line" | awk -F ':' '{print $1}')
-            line_number=$(echo "$line" | awk -F ':' '{print $2}')
-            severity=$(echo "$line" | awk -F ':' '{print $3}')
-            message=$(echo "$line" | awk -F ':' '{print $4}')
-            echo "::error file=$file,line=$line_number::$severity $message"
-          done
-          line_count=$(grep --invert-match "./libs/myteams" coding-style-reports.log | wc -l)
-          if [ "$line_count" -gt 6 ]; then
-            echo "::error::Too many style errors"
-            exit 1
-          fi
+            check.sh $(pwd) $(pwd)
+            while IFS= read -r line; do
+              file=$(echo "$line" | awk -F ':' '{print $1}')
+              line_number=$(echo "$line" | awk -F ':' '{print $2}')
+              severity=$(echo "$line" | awk -F ':' '{print $3}')
+              message=$(echo "$line" | awk -F ':' '{print $4}')
+              echo "::error file=$file,line=$line_number::$severity $message"
+            done < coding-style-reports.log
+            line_count=$(wc -l coding-style-reports.log | awk '{print $1}')
+            if [ "$line_count" -gt 6 ]; then
+              echo "::error::Too many style errors"
+              exit 1
+            fi
 
   compile_and_run_tests:
     needs: check_coding_style
